blank_issues_enabled: false
contact_links:
  - name: Contributing Guide
    url: https://github.com/redcode-labs/.github/blob/main/CONTRIBUTING.md
    about: Before submitting an issue or a PR, we recommend reading our CONTRIBUTING.md file