name: Feature request
description: Request an enhancement for the project
labels: [enhancement]
body: 

  - type: markdown
    attributes:
      value: |
        Before requesting: search currently [exisiting feature requests](https://github.com/search?q=user%3Aredcode-labs+label%3Aenhancement+is%3Aopen&type=issues&ref=advsearch)

  - type: textarea
    attributes:
      label: "Problem"
      description: "Is your feature request related to a problem? If so, please describe. If relevant, include references to other projects"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Solution"
      description: "Description of what you want to happen"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Additional context"
      description: "Add any other context or screenshots about the feature request in this section"
    validations:
      required: false